# Generated by Django 3.2.8 on 2021-10-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chooice_text',
            new_name='choice_text',
        ),
    ]
